version: '3'

services:
  SOS360DB:
    image: 'bitnami/postgresql'
    ports:
      - '5432:5432'
    volumes:
      - './postgresql_data:/bitnami/postgresql'
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - docker-network

  SOS360API:
    working_dir: /usr/app
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile

networks:
  docker-network: