version: "3.9"

services:
  sos360api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nestjs-api
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - sos360db

  sos360db:
    image: 'bitnami/postgresql'
    container_name: postgres-db
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - postgres-data:/bitnami/postgresql
    restart: unless-stopped
    networks:
      - db_network

volumes:
  postgres-data:

networks:
  db_network:
    driver: bridge

